-- MaxDex: full ability table (renumbered, 289 valid IDs). Loaded by MaxDexExtension to replace
-- the tracker's vanilla AbilityData.Abilities (78 entries) so high-id randomized abilities resolve.
MaxDexAbilities = {
	{ id = 1, name = "Stench" },
	{ id = 2, name = "Drizzle" },
	{ id = 3, name = "Speed Boost" },
	{ id = 4, name = "Battle Armor" },
	{ id = 5, name = "Sturdy" },
	{ id = 6, name = "Damp" },
	{ id = 7, name = "Limber" },
	{ id = 8, name = "Sand Veil" },
	{ id = 9, name = "Static" },
	{ id = 10, name = "Volt Absorb" },
	{ id = 11, name = "Water Absorb" },
	{ id = 12, name = "Oblivious" },
	{ id = 13, name = "Cloud Nine" },
	{ id = 14, name = "Compoundeyes" },
	{ id = 15, name = "Insomnia" },
	{ id = 16, name = "Color Change" },
	{ id = 17, name = "Immunity" },
	{ id = 18, name = "Flash Fire" },
	{ id = 19, name = "Shield Dust" },
	{ id = 20, name = "Own Tempo" },
	{ id = 21, name = "Suction Cups" },
	{ id = 22, name = "Intimidate" },
	{ id = 23, name = "Shadow Tag" },
	{ id = 24, name = "Rough Skin" },
	{ id = 25, name = "Wonder Guard" },
	{ id = 26, name = "Levitate" },
	{ id = 27, name = "Effect Spore" },
	{ id = 28, name = "Synchronize" },
	{ id = 29, name = "Clear Body" },
	{ id = 30, name = "Natural Cure" },
	{ id = 31, name = "Lightningrod" },
	{ id = 32, name = "Serene Grace" },
	{ id = 33, name = "Swift Swim" },
	{ id = 34, name = "Chlorophyll" },
	{ id = 35, name = "Illuminate" },
	{ id = 36, name = "Trace" },
	{ id = 37, name = "Huge Power" },
	{ id = 38, name = "Poison Point" },
	{ id = 39, name = "Inner Focus" },
	{ id = 40, name = "Magma Armor" },
	{ id = 41, name = "Water Veil" },
	{ id = 42, name = "Magnet Pull" },
	{ id = 43, name = "Soundproof" },
	{ id = 44, name = "Rain Dish" },
	{ id = 45, name = "Sand Stream" },
	{ id = 46, name = "Pressure" },
	{ id = 47, name = "Thick Fat" },
	{ id = 48, name = "Early Bird" },
	{ id = 49, name = "Flame Body" },
	{ id = 50, name = "Run Away" },
	{ id = 51, name = "Keen Eye" },
	{ id = 52, name = "Hyper Cutter" },
	{ id = 53, name = "Pickup" },
	{ id = 54, name = "Truant" },
	{ id = 55, name = "Hustle" },
	{ id = 56, name = "Cute Charm" },
	{ id = 57, name = "Plus" },
	{ id = 58, name = "Minus" },
	{ id = 59, name = "Forecast" },
	{ id = 60, name = "Sticky Hold" },
	{ id = 61, name = "Shed Skin" },
	{ id = 62, name = "Guts" },
	{ id = 63, name = "Marvel Scale" },
	{ id = 64, name = "Liquid Ooze" },
	{ id = 65, name = "Overgrow" },
	{ id = 66, name = "Blaze" },
	{ id = 67, name = "Torrent" },
	{ id = 68, name = "Swarm" },
	{ id = 69, name = "Rock Head" },
	{ id = 70, name = "Drought" },
	{ id = 71, name = "Arena Trap" },
	{ id = 72, name = "Vital Spirit" },
	{ id = 73, name = "White Smoke" },
	{ id = 74, name = "Pure Power" },
	{ id = 75, name = "Shell Armor" },
	{ id = 76, name = "Cacophony" },
	{ id = 77, name = "Air Lock" },
	{ id = 78, name = "Tangled Feet" },
	{ id = 79, name = "Motor Drive" },
	{ id = 80, name = "Rivalry" },
	{ id = 81, name = "Steadfast" },
	{ id = 82, name = "Snow Cloak" },
	{ id = 83, name = "Anger Point" },
	{ id = 84, name = "Heatproof" },
	{ id = 85, name = "Simple" },
	{ id = 86, name = "Dry Skin" },
	{ id = 87, name = "Download" },
	{ id = 88, name = "Iron Fist" },
	{ id = 89, name = "Poison Heal" },
	{ id = 90, name = "Adaptability" },
	{ id = 91, name = "Skill Link" },
	{ id = 92, name = "Hydration" },
	{ id = 93, name = "Solar Power" },
	{ id = 94, name = "Quick Feet" },
	{ id = 95, name = "Normalize" },
	{ id = 96, name = "Sniper" },
	{ id = 97, name = "Magic Guard" },
	{ id = 98, name = "No Guard" },
	{ id = 99, name = "Stall" },
	{ id = 100, name = "Technician" },
	{ id = 101, name = "Leaf Guard" },
	{ id = 102, name = "Klutz" },
	{ id = 103, name = "Mold Breaker" },
	{ id = 104, name = "Super Luck" },
	{ id = 105, name = "Aftermath" },
	{ id = 106, name = "Anticipation" },
	{ id = 107, name = "Forewarn" },
	{ id = 108, name = "Unaware" },
	{ id = 109, name = "Tinted Lens" },
	{ id = 110, name = "Filter" },
	{ id = 111, name = "Slow Start" },
	{ id = 112, name = "Scrappy" },
	{ id = 113, name = "Storm Drain" },
	{ id = 114, name = "Ice Body" },
	{ id = 115, name = "Solid Rock" },
	{ id = 116, name = "Snow Warning" },
	{ id = 117, name = "Frisk" },
	{ id = 118, name = "Reckless" },
	{ id = 119, name = "Flower Gift" },
	{ id = 120, name = "Bad Dreams" },
	{ id = 121, name = "Sheer Force" },
	{ id = 122, name = "Contrary" },
	{ id = 123, name = "Unnerve" },
	{ id = 124, name = "Defiant" },
	{ id = 125, name = "Defeatist" },
	{ id = 126, name = "Weak Armor" },
	{ id = 127, name = "Heavy Metal" },
	{ id = 128, name = "Light Metal" },
	{ id = 129, name = "Multiscale" },
	{ id = 130, name = "Toxic Boost" },
	{ id = 131, name = "Flare Boost" },
	{ id = 132, name = "Harvest" },
	{ id = 133, name = "Moody" },
	{ id = 134, name = "Overcoat" },
	{ id = 135, name = "Poison Touch" },
	{ id = 136, name = "Big Pecks" },
	{ id = 137, name = "Sand Rush" },
	{ id = 138, name = "Wonder Skin" },
	{ id = 139, name = "Analytic" },
	{ id = 140, name = "Infiltrator" },
	{ id = 141, name = "Moxie" },
	{ id = 142, name = "Justified" },
	{ id = 143, name = "Rattled" },
	{ id = 144, name = "Magic Bounce" },
	{ id = 145, name = "Sap Sipper" },
	{ id = 146, name = "Prankster" },
	{ id = 147, name = "Sand Force" },
	{ id = 148, name = "Iron Barbs" },
	{ id = 149, name = "Victory Star" },
	{ id = 150, name = "Aroma Veil" },
	{ id = 151, name = "Flower Veil" },
	{ id = 152, name = "Bulletproof" },
	{ id = 153, name = "Competitive" },
	{ id = 154, name = "Strong Jaw" },
	{ id = 155, name = "Sweet Veil" },
	{ id = 156, name = "Gale Wings" },
	{ id = 157, name = "Mega Launcher" },
	{ id = 158, name = "Tough Claws" },
	{ id = 159, name = "Gooey" },
	{ id = 160, name = "Delta Stream" },
	{ id = 161, name = "Stamina" },
	{ id = 162, name = "Water Compaction" },
	{ id = 163, name = "Berserk" },
	{ id = 164, name = "Slush Rush" },
	{ id = 165, name = "Long Reach" },
	{ id = 166, name = "Comatose" },
	{ id = 167, name = "Fluffy" },
	{ id = 168, name = "Soul Heart" },
	{ id = 169, name = "Tangling Hair" },
	{ id = 170, name = "Full Metal Body" },
	{ id = 171, name = "Prism Armor" },
	{ id = 172, name = "Mirror Armor" },
	{ id = 173, name = "Steam Engine" },
	{ id = 174, name = "Punk Rock" },
	{ id = 175, name = "Neutralizing Gas" },
	{ id = 176, name = "Pastel Veil" },
	{ id = 177, name = "Thermal Exchange" },
	{ id = 178, name = "Purifying Salt" },
	{ id = 179, name = "Well Baked Body" },
	{ id = 180, name = "Guard Dog" },
	{ id = 181, name = "Good As Gold" },
	{ id = 182, name = "Vessel Of Ruin" },
	{ id = 183, name = "Sword Of Ruin" },
	{ id = 184, name = "Tablets Of Ruin" },
	{ id = 185, name = "Beads Of Ruin" },
	{ id = 186, name = "Opportunist" },
	{ id = 187, name = "Sharpness" },
	{ id = 188, name = "Armor Tail" },
	{ id = 189, name = "Earth Eater" },
	{ id = 190, name = "Mind's Eye" },
	{ id = 191, name = "Supersweet Syrup" },
	{ id = 192, name = "Pixilate" },
	{ id = 193, name = "Refrigerate" },
	{ id = 194, name = "Aerilate" },
	{ id = 195, name = "Galvanize" },
	{ id = 196, name = "Gluttony" },
	{ id = 197, name = "Unburden" },
	{ id = 198, name = "Honey Gather" },
	{ id = 199, name = "Pickpocket" },
	{ id = 200, name = "Cursed Body" },
	{ id = 201, name = "Healer" },
	{ id = 202, name = "Friend Guard" },
	{ id = 203, name = "Telepathy" },
	{ id = 204, name = "Regenerator" },
	{ id = 205, name = "Illusion" },
	{ id = 206, name = "Mummy" },
	{ id = 207, name = "Turboblaze" },
	{ id = 208, name = "Teravolt" },
	{ id = 209, name = "Cheek Pouch" },
	{ id = 210, name = "Protean" },
	{ id = 211, name = "Fur Coat" },
	{ id = 212, name = "Magician" },
	{ id = 213, name = "Grass Pelt" },
	{ id = 214, name = "Symbiosis" },
	{ id = 215, name = "Parental Bond" },
	{ id = 216, name = "Dark Aura" },
	{ id = 217, name = "Fairy Aura" },
	{ id = 218, name = "Aura Break" },
	{ id = 219, name = "Primordial Sea" },
	{ id = 220, name = "Desolate Land" },
	{ id = 221, name = "Wimp Out" },
	{ id = 222, name = "Emergency Exit" },
	{ id = 223, name = "Merciless" },
	{ id = 224, name = "Stakeout" },
	{ id = 225, name = "Water Bubble" },
	{ id = 226, name = "Steelworker" },
	{ id = 227, name = "Liquid Voice" },
	{ id = 228, name = "Triage" },
	{ id = 229, name = "Surge Surfer" },
	{ id = 230, name = "Corrosion" },
	{ id = 231, name = "Queenly Majesty" },
	{ id = 232, name = "Innards Out" },
	{ id = 233, name = "Dancer" },
	{ id = 234, name = "Battery" },
	{ id = 235, name = "Dazzling" },
	{ id = 236, name = "Receiver" },
	{ id = 237, name = "Power Of Alchemy" },
	{ id = 238, name = "Beast Boost" },
	{ id = 239, name = "Electric Surge" },
	{ id = 240, name = "Psychic Surge" },
	{ id = 241, name = "Misty Surge" },
	{ id = 242, name = "Grassy Surge" },
	{ id = 243, name = "Shadow Shield" },
	{ id = 244, name = "Neuroforce" },
	{ id = 245, name = "Intrepid Sword" },
	{ id = 246, name = "Dauntless Shield" },
	{ id = 247, name = "Libero" },
	{ id = 248, name = "Ball Fetch" },
	{ id = 249, name = "Cotton Down" },
	{ id = 250, name = "Propeller Tail" },
	{ id = 251, name = "Stalwart" },
	{ id = 252, name = "Sand Spit" },
	{ id = 253, name = "Ice Scales" },
	{ id = 254, name = "Ripen" },
	{ id = 255, name = "Power Spot" },
	{ id = 256, name = "Mimicry" },
	{ id = 257, name = "Screen Cleaner" },
	{ id = 258, name = "Steely Spirit" },
	{ id = 259, name = "Perish Body" },
	{ id = 260, name = "Wandering Spirit" },
	{ id = 261, name = "Gorilla Tactics" },
	{ id = 262, name = "Quick Draw" },
	{ id = 263, name = "Unseen Fist" },
	{ id = 264, name = "Curious Medicine" },
	{ id = 265, name = "Transistor" },
	{ id = 266, name = "Dragon's Maw" },
	{ id = 267, name = "Chilling Neigh" },
	{ id = 268, name = "Grim Neigh" },
	{ id = 269, name = "As One-IR" },
	{ id = 270, name = "As One-SR" },
	{ id = 271, name = "Lingering Aroma" },
	{ id = 272, name = "Seed Sower" },
	{ id = 273, name = "Anger Shell" },
	{ id = 274, name = "Wind Rider" },
	{ id = 275, name = "Rocky Payload" },
	{ id = 276, name = "Wind Power" },
	{ id = 277, name = "Electromorphosis" },
	{ id = 278, name = "Protosynthesis" },
	{ id = 279, name = "Quark Drive" },
	{ id = 280, name = "Orichalcum Pulse" },
	{ id = 281, name = "Hadron Engine" },
	{ id = 282, name = "Cud Chew" },
	{ id = 283, name = "Supreme Overlord" },
	{ id = 284, name = "Costar" },
	{ id = 285, name = "Toxic Debris" },
	{ id = 286, name = "Mycelium Might" },
	{ id = 287, name = "Hospitality" },
	{ id = 288, name = "Toxic Chain" },
	{ id = 289, name = "Poison Puppeteer" },
}